### PR TITLE
Changes I required to get Modizer to build on an Apple Silicon DTK.

### PR DESCRIPTION
**Pull request by tarasis**
(ignoring the changes to modizer/modizer.xcodeproj/project.pbxproj which I can't seem to delete from the pull request)

I have to make all of these changes to get modizer to build on the Apple Silicon DTK.

### CODE REVIEW

**Comment by tarasis** [comment]
At the moment it will compile and run as a Mac app however there are some visual issues (like the album art is too low). If I can I'll take a stab at that.

**Comment by yoyofr** [comment]
thanks, I will have a look

**Comment by yoyofr** [comment]
Hello,
I did equivalent changes, it now compiles and run on apple silicon/M1 (in My Mac (designed for iPad) mode).

**Comment by tarasis** [comment]
Fab news, thank you and I look forward to the 2.9.4 release!

And dang > < this close to having my first PR accept :)

**Comment by yoyofr** [comment]
I will also try to clean up the folders structure & make headers path relative as much as possible, right now it's a big mess

**Pull request closed without merging**
